version: '3'
services:

  ace-db:
    image: mysql:8.0.22
    container_name: ace-db
    env_file:
      - docker.env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306/tcp"
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  ace-server:
    build: .
    image: acemulator/ace:latest
    depends_on:
      - ace-db
    container_name: ace-server
    env_file:
      - docker.env
    volumes:
      - ./Config:/ace/Config
      - ./Content:/ace/Content
      - ./Dats:/ace/Dats
      - ./Logs:/ace/Logs
    ports:
      - "9000-9001:9000-9001/udp"
    #restart: unless-stopped
    restart: on-failure

  ace-web:
    build:
      context: ../../
      dockerfile: apps/efd-web/Dockerfile
    depends_on:
      - ace-db
    container_name: ace-web
    volumes:
      - ../efd-web:/app
    ports:
      - "3000:3000"
    #restart: unless-stopped
    restart: on-failure

