---
- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny

- name: UFW - Allow  HTTP Server
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: UFW - Allow HTTPS Server
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: UFW - Allow ACE Server UDP Connections
  community.general.ufw:
    rule: allow
    port: 9000:9020
    proto: udp

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH
