version: '3'
services:
  ace-db:
    image: 'mysql:8.0.12'
    container_name: ace-db
    env_file:
      - docker.env
    volumes:
      - './db-data:/var/lib/mysql'
    ports:
      - '3306:3306/tcp'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-h'
        - localhost
  ace-workbench:
    image: 'lscr.io/linuxserver/mysql-workbench:latest'
    depends_on:
      - ace-db
    container_name: mysql-workbench
    env_file:
      - docker.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '3000:3000'
      - '3001:3001'
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  ace-server:
    build: .
    image: 'acemulator/ace:latest'
    depends_on:
      - ace-db
    container_name: ace-server
    env_file:
      - docker.env
    volumes:
      - './Config:/ace/Config'
      - './Content:/ace/Content'
      - './Dats:/ace/Dats'
      - './Logs:/ace/Logs'
    ports:
      - '9000-9001:9000-9001/udp'
    restart: on-failure

